---
title: "cha 8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(dplyr)
library(ggplot2)
```

```{r}
#### 1. Load Data ####
df <- read.csv("D:/Data Science for Marketing-I/dataset/WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv", 
  header=TRUE, 
  sep=","
)
```
#### 2. Variable Encoding ####

```{r}
## 2.1. Response Variable: Response
df$Engaged <- rep(0,nrow(df))
df$Engaged[df$Response=='Yes']=1
mean(df$Engaged)
```

```{r}
## 2.2. Categorical Features
categoricalVars = c(
  'Sales.Channel', 'Vehicle.Size', 'Vehicle.Class', 'Policy', 'Policy.Type',
  'EmploymentStatus', 'Marital.Status', 'Education', 'Coverage', 'Gender'
)

encodedDF <- model.matrix(~.-1, df[categoricalVars])
```

```{r}
## 2.3. Continuous Features
continuousFeatures <- c(
  'Customer.Lifetime.Value', 'Income', 'Monthly.Premium.Auto',
  'Months.Since.Last.Claim', 'Months.Since.Policy.Inception',
  'Number.of.Open.Complaints', 'Number.of.Policies', 'Total.Claim.Amount'
)

encodedDF <- cbind(encodedDF, df[continuousFeatures])
```

#### 3. Training & Testing ####

```{r}
# install.packages('caTools')
library(caTools)
```

```{r}
set.seed(123)
sample <- sample.split(df$Customer, SplitRatio = .7)
```

```{r}
trainX <- as.matrix(subset(encodedDF, sample == TRUE))
trainY <- as.double(as.matrix(subset(df$Engaged, sample == TRUE)))
```

```{r}
testX <- as.matrix(subset(encodedDF, sample == FALSE))
testY <- as.double(as.matrix(subset(df$Engaged, sample == FALSE)))
```

## 3.1. Building Random Forest Model

# - Training
```{r}
# install.packages('randomForest')
library(randomForest)
```
```{r}
rfModel <- randomForest(x=trainX, y=factor(trainY), ntree=200, maxnodes=24)
```

```{r}
# - Individual Tree Predictions
getTree(rfModel, 1)
predict(rfModel, trainX, predict.all=TRUE)$individual
```

```{r}
# - Feature Importances
importance(rfModel)
```

## 3.2. Evaluating Models

```{r}
inSamplePreds <- as.double(predict(rfModel, trainX)) - 1
outSamplePreds <- as.double(predict(rfModel, testX)) - 1
```

```{r}
# - Accuracy, Precision, and Recall
inSampleAccuracy <- mean(trainY == inSamplePreds)
outSampleAccuracy <- mean(testY == outSamplePreds)
print(sprintf('In-Sample Accuracy: %0.4f', inSampleAccuracy))
print(sprintf('Out-Sample Accuracy: %0.4f', outSampleAccuracy))

inSamplePrecision <- sum(inSamplePreds & trainY) / sum(inSamplePreds)
outSamplePrecision <- sum(outSamplePreds & testY) / sum(outSamplePreds)
print(sprintf('In-Sample Precision: %0.4f', inSamplePrecision))
print(sprintf('Out-Sample Precision: %0.4f', outSamplePrecision))

inSampleRecall <- sum(inSamplePreds & trainY) / sum(trainY)
outSampleRecall <- sum(outSamplePreds & testY) / sum(testY)
print(sprintf('In-Sample Recall: %0.4f', inSampleRecall))
print(sprintf('Out-Sample Recall: %0.4f', outSampleRecall))
```

# - ROC & AUC
```{r}
# install.packages('ROCR')
library(ROCR)
```

```{r}
inSamplePredProbs <- as.double(predict(rfModel, trainX, type='prob')[,2])
outSamplePredProbs <- as.double(predict(rfModel, testX, type='prob')[,2])

pred <- prediction(outSamplePredProbs, testY)
perf <- performance(pred, measure = "tpr", x.measure = "fpr") 
auc <- performance(pred, measure='auc')@y.values[[1]]

plot(
  perf, 
  main=sprintf('Random Forest Model ROC Curve (AUC: %0.2f)', auc), 
  col='darkorange', 
  lwd=2
) + grid()
abline(a = 0, b = 1, col='darkgray', lty=3, lwd=2)
```
```{r}
inSamplePredProbs <- as.double(predict(rfModel, trainX, type='prob')[,2])
outSamplePredProbs <- as.double(predict(rfModel, testX, type='prob')[,2])
#in sample
pred_in <- prediction(inSamplePredProbs, testY)
perf_in <- performance(pred_in, measure = "tpr", x.measure = "fpr") 
auc_in <- performance(pred_in, measure='auc')@y.values[[1]]
#out sample
pred_out <- prediction(outSamplePredProbs, testY)
perf_out <- performance(pred_out, measure = "tpr", x.measure = "fpr") 
auc_out <- performance(pred_out, measure='auc')@y.values[[1]]

plot(
  perf, 
  main=sprintf('Random Forest Model ROC Curve (AUC: %0.2f)', auc), 
  col='darkorange', 
  lwd=2
) + grid()
abline(a = 0, b = 1, col='darkgray', lty=3, lwd=2)
```
