---
title: "day 1"
author: "gowtham_1p23mb010"
date: "2024-12-09"
output: html_document
---
```{r}
library(dplyr)
library(ggplot2)
```

```{r}
df = read.csv("D:/Data Science for Marketing-I/data/bank-additional-full.csv",sep = ';')
df
```
```{r}
dim(df)
str(df)
```
```{r}
head(df)
```
```{r}
table(df$age)
```


```{r}
df$conversion = ifelse(df$y == "yes", 1, 0)
df$conversion
```

```{r}
table(df$conversion)
```
```{r}
mean(df$conversion) * 100
```
```{r}
df$conversion=rep(0,nrow(df))
df$conversion[df$y=='yes']=1
df$conversion
```
```{r}
print(sum(df$conversion)/nrow(df)*100.0)
```
```{r}
result=df%>%group_by(campaign)%>%summarise(total_count=n(),total_conversion=sum(conversion))%>%mutate(c_rate=total_conversion/total_count*100)
result
```

```{r}
resut=df%>%group_by(age)%>%summarise(total_count=n(),total_conversion=sum(age))%>%mutate(c_rate=total_conversion/total_count*100)
resut
```

```{r}
df |>
  group_by(campaign) |>
  summarise(
    total_count = n(),
    total_conversion = sum(conversion)
  ) |>
mutate(c_rate = total_conversion / total_count * 100)

```

```{r}
ggplot(result,aes(x=campaign,y=c_rate))+geom_line()
```
































































































































































































































































































